name: Release

on:
  push:
    tags:
      - '*'

permissions:
  contents: write

jobs:
  build:
    name: Build (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
      - name: Cache cargo
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: ". -> target"
      - name: Build
        run: cargo build --release
      - name: Prepare binary archive
        shell: bash
        run: |
          set -e
          if [[ "${{ matrix.os }}" == "windows-latest" ]]; then
            7z a backup-to-cloud-windows.zip target/release/backup-to-cloud.exe
          else
            zip backup-to-cloud-linux.zip target/release/backup-to-cloud
          fi
      - name: Upload zipped binary
        uses: actions/upload-artifact@v6
        with:
          name: backup-to-cloud-${{ matrix.os }}
          path: |
            backup-to-cloud-windows.zip
            backup-to-cloud-linux.zip
          retention-days: 7
        

  release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Generate release notes
        uses: orhun/git-cliff-action@v4
        with:
          args: --latest --output RELEASE_NOTES.md
      - name: Download all zipped binaries
        uses: actions/download-artifact@v7
        with:
          path: dist
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/**/*.zip
          body_path: RELEASE_NOTES.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
